<a href="https://colab.research.google.com/github/ddy623/Kaggle-Projects/blob/main/Copy_of_titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

In [ ]:
# Load Data
fpath = '/content/drive/MyDrive/Colab Notebooks/Data Science Project/test.csv'
df = pd.read_csv(fpath)
df.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [ ]:
df.tail()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB

In [ ]:
df.describe()

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

Remove cabin from dataset

In [ ]:
# Reload test.csv into df
fpath_test = '/content/drive/MyDrive/Colab Notebooks/Data Science Project/test.csv'
df = pd.read_csv(fpath_test)

# Remove the 'Cabin' column
df.drop('Cabin', axis=1, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(4)
memory usage: 32.8+ KB

### Handling Missing Values in 'Age' Column

First, let's examine the extent of missing data in the 'Age' column.

In [ ]:
print(f"Missing values in 'Age' column before imputation: {df['Age'].isnull().sum()}")

Missing values in 'Age' column before imputation: 86

Now, we will impute the missing 'Age' values using the median of the column. The median is often preferred over the mean for age, as it's less sensitive to outliers.

In [ ]:
median_age = df['Age'].median()
df['Age'].fillna(median_age, inplace=True)
print(f"Median Age used for imputation: {median_age}")

Median Age used for imputation: 27.0

/tmp/ipykernel_1882/1841100376.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(median_age, inplace=True)

Finally, let's verify that all missing values in the 'Age' column have been handled.

In [ ]:
print(f"Missing values in 'Age' column after imputation: {df['Age'].isnull().sum()}")
df.info()

Missing values in 'Age' column after imputation: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          418 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(4)
memory usage: 32.8+ KB

In [ ]:
# Check for missing values in 'Fare'
print(f"Missing values in 'Fare' column before imputation: {df['Fare'].isnull().sum()}")

# Impute missing 'Fare' values with the median
median_fare = df['Fare'].median()
df['Fare'].fillna(median_fare, inplace=True)
print(f"Median Fare used for imputation: {median_fare}")

# Verify that missing values have been handled
print(f"Missing values in 'Fare' column after imputation: {df['Fare'].isnull().sum()}")
df.info()

Missing values in 'Fare' column before imputation: 1
Median Fare used for imputation: 14.4542
Missing values in 'Fare' column after imputation: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          418 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         418 non-null    float64
 9   Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(4)
memory usage: 32.8+ KB

/tmp/ipykernel_1882/2563009657.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Fare'].fillna(median_fare, inplace=True)

Upload train data

In [ ]:
#Load Data
fpath = '/content/drive/MyDrive/Colab Notebooks/Data Science Project/train.csv'
df = pd.read_csv(fpath)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.drop('Cabin', axis=1, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

In [ ]:
# Check for missing values in 'Age'
print(f"Missing values in 'Age' column before imputation: {df['Age'].isnull().sum()}")

# Impute missing 'Age' values with the median
median_age = df['Age'].median()
df['Age'].fillna(median_age, inplace=True)
print(f"Median Age used for imputation: {median_age}")

# Verify that missing values have been handled
print(f"Missing values in 'Age' column after imputation: {df['Age'].isnull().sum()}")
df.info()

Missing values in 'Age' column before imputation: 177
Median Age used for imputation: 28.0
Missing values in 'Age' column after imputation: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

/tmp/ipykernel_1882/171024667.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(median_age, inplace=True)

In [ ]:
# Check for missing values in 'Embarked'
print(f"Missing values in 'Embarked' column before imputation: {df['Embarked'].isnull().sum()}")

# Impute missing 'Embarked' values with the mode
mode_embarked = df['Embarked'].mode()[0] # .mode() returns a Series, so we take the first element
df['Embarked'].fillna(mode_embarked, inplace=True)
print(f"Mode of Embarked used for imputation: {mode_embarked}")

# Verify that missing values have been handled
print(f"Missing values in 'Embarked' column after imputation: {df['Embarked'].isnull().sum()}")
df.info()

Missing values in 'Embarked' column before imputation: 2
Mode of Embarked used for imputation: S
Missing values in 'Embarked' column after imputation: 0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

/tmp/ipykernel_1882/3135569189.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Embarked'].fillna(mode_embarked, inplace=True)

In [ ]:
print("In the 'Survived' column:")
print("0 = Did not survive (Death)")
print("1 = Survived")

In the 'Survived' column:
0 = Did not survive (Death)
1 = Survived

In [ ]:
# Prepare the data
# Drop irrelevant columns for modeling
df_ml = df.drop(['Name', 'Ticket', 'PassengerId'], axis=1)

# Convert 'Sex' and 'Embarked' to numerical using LabelEncoder or one-hot encoding
# For simplicity and to avoid too many columns for now, let's use LabelEncoder for 'Sex' and one-hot for 'Embarked'

# Label Encoding for 'Sex'
le = LabelEncoder()
df_ml['Sex'] = le.fit_transform(df_ml['Sex'])

# One-Hot Encoding for 'Embarked'
df_ml = pd.get_dummies(df_ml, columns=['Embarked'], drop_first=True)

# Define features (X) and target (y)
X = df_ml.drop('Survived', axis=1)
y = df_ml['Survived']

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train the RandomForestClassifier model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.4f}")

# Display feature importances
feature_importances = pd.Series(model.feature_importances_, index=X.columns).sort_values(ascending=False)
print("\nFeature Importances:")
print(feature_importances)

Model Accuracy: 0.8101

Feature Importances:
Fare          0.279199
Sex           0.266967
Age           0.249413
Pclass        0.081051
SibSp         0.053500
Parch         0.035840
Embarked_S    0.024301
Embarked_Q    0.009729
dtype: float64

In [ ]:
num_survived = df['Survived'].sum()
print(f"Number of people who survived the Titanic: {int(num_survived)}")

Number of people who survived the Titanic: 342

In [ ]:
num_died = (df['Survived'] == 0).sum()
print(f"Number of people who died in the Titanic: {int(num_died)}")

Number of people who died in the Titanic: 549

Based on the data, 549 people died in the Titanic and 342 people survived.